server.port=8081
spring.application.name=practica10-bully

# ID de este proceso (1,2,3) - cambiar al iniciar en cada terminal
bully.process-id=1

# IPs de los 3 procesos (por defecto localhost para desarrollo local fácil)
bully.peers[0].id=1
bully.peers[0].ip=127.0.0.1
bully.peers[0].puerto=8081

bully.peers[1].id=2
bully.peers[1].ip=127.0.0.1
bully.peers[1].puerto=8082

bully.peers[2].id=3
bully.peers[2].ip=127.0.0.1
bully.peers[2].puerto=8083

# Coordinador inicial (el de mayor ID)
bully.coordinador-inicial=3

# Timeout en ms para esperar respuestas OK durante elección
bully.timeout-ms=2000
