server.port=8085
spring.application.name=practica10-bully

# ID de este proceso (1,2,3,4,5) - cambiar en cada m�quina
bully.process-id=1

# IPs de los 5 procesos (editar seg�n red local)
bully.peers[0].id=1
bully.peers[0].ip=192.168.1.10
bully.peers[0].puerto=8085
bully.peers[1].id=2
bully.peers[1].ip=192.168.1.11
bully.peers[1].puerto=8085
bully.peers[2].id=3
bully.peers[2].ip=192.168.1.12
bully.peers[2].puerto=8085
bully.peers[3].id=4
bully.peers[3].ip=192.168.1.13
bully.peers[3].puerto=8085
bully.peers[4].id=5
bully.peers[4].ip=192.168.1.14
bully.peers[4].puerto=8085

# Coordinador inicial
bully.coordinador-inicial=5

# Timeout en ms para esperar respuestas OK durante elecci�n
bully.timeout-ms=5000
